{
 "title": "General Dashboard",
 "tags": [
  "imo",
  "base"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "envoy",
    "query": {
     "query": "label_values(imo_server_live,envoy)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status: $envoy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "repeat": "envoy",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "imo_server_live{envoy=\"$envoy\"}",
     "legendFormat": "state"
    },
    {
     "expr": "rate(imo_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=\"jaeger_stats\", envoy=\"$envoy\"}[$__rate_interval]) + ignoring(envoy_cluster_name) rate(imo_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=\"otlp_stats_dyn\", envoy=\"$envoy\"}[$__rate_interval])",
     "legendFormat": "stats bw"
    },
    {
     "expr": "imo_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=\"xds_cluster\", envoy=\"$envoy\"}",
     "legendFormat": "controller.sent"
    },
    {
     "expr": "imo_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name=\"xds_cluster\", envoy=\"$envoy\"}",
     "legendFormat": "controller.rcv"
    }
   ]
  },
  { "title": "Protocol Dashboards", "type": "dashlist", "gridPos": { "h": 7, "w": 3, "x": 0, "y": 4 } },
  {
   "title": "Active Clusters",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "imo_cluster_manager_active_clusters",
     "legendFormat": "{{envoy}}"
    }
   ]
  },
  {
   "title": "Incoming active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "imo_listener_downstream_cx_active{envoy_listener_address!=\"0.0.0.0_4319\"}",
     "legendFormat": "{{envoy}}.{{envoy_listener_address}}"
    }
   ]
  },
  {
   "title": "Traffic sent from Upstream Node ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(imo_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name!~\"jaeger_stats|otlp_stats|xds_cluster|otlp_stats_dyn\"}[$__rate_interval])",
     "legendFormat": "{{envoy}}.{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Traffic returned to Upstream Node ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(imo_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name!~\"jaeger_stats|otlp_stats|xds_cluster|otlp_stats_dyn\"}[$__rate_interval])",
     "legendFormat": "{{envoy}}.{{envoy_cluster_name}}"
    }
   ]
  }
 ]
}