{
 "title": "HTTP2",
 "tags": [
  "imo",
  "protocol",
  "http",
  "http2"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Envoy http2 recorded metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "imo_cluster_http2_outbound_control_frames_active{envoy_cluster_name!~\"jaeger_stats|otlp_stats\"}",
     "legendFormat": "{{envoy}}.{{envoy_cluster_name}}.{{__name__}}"
    },
    {
     "expr": "imo_cluster_http2_outbound_frames_active{envoy_cluster_name!~\"jaeger_stats|otlp_stats\"}",
     "legendFormat": "{{envoy}}.{{envoy_cluster_name}}.{{__name__}}"
    },
    {
     "expr": "imo_cluster_http2_pending_send_bytes{envoy_cluster_name!~\"jaeger_stats|otlp_stats\"}",
     "legendFormat": "{{envoy}}.{{envoy_cluster_name}}.{{__name__}"
    },
    {
     "expr": "imo_cluster_http2_streams_active{envoy_cluster_name!~\"jaeger_stats|otlp_stats\"}",
     "legendFormat": "{{envoy}}.{{envoy_cluster_name}}.{{__name__}}"
    }
   ]
  },
  {
   "title": "Flow control",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "imo_cluster_upstream_flow_control_paused_reading_total",
     "legendFormat": "{{envoy}}.{{envoy_cluster_name}}.read_pause"
    },
    {
     "expr": "imo_cluster_upstream_flow_control_resumed_reading_total",
     "legendFormat": "{{envoy}}.{{envoy_cluster_name}}.read_resume"
    },
    {}
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "imo_http_downstream_cx_tx_bytes_buffered",
     "legendFormat": "__auto"
    },
    {
     "expr": "imo_cluster_upstream_cx_http2_total{envoy=\"nginxP\", envoy_cluster_name!~\"jaeger_stats|otlp_stats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "imo_cluster_upstream_cx_rx_bytes_buffered{envoy=\"nginxP\", envoy_cluster_name!~\"jaeger_stats|otlp_stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "imo_cluster_upstream_cx_destroy_total{envoy_cluster_name!~\"otlp_stats|jaeger_stats\"}",
     "legendFormat": "{{envoy}}.{{envoy_cluster_name}}.{{__name__}}"
    },
    {
     "expr": "imo_cluster_upstream_cx_destroy_with_active_rq_total",
     "legendFormat": "{{envoy}}.{{envoy_cluster_name}}.{{__name__}}"
    },
    {
     "expr": "imo_cluster_upstream_cx_destroy_remote_with_active_rq_total",
     "legendFormat": "{{envoy}}.{{envoy_cluster_name}}.{{__name__}}"
    },
    {
     "expr": "imo_cluster_upstream_cx_destroy_local_total",
     "legendFormat": "{{envoy}}.{{envoy_cluster_name}}.{{__name__}}"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 9, "w": 3, "x": 0, "y": 16 } },
  {
   "title": "ssl handshake",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 16 },
   "targets": [
    {
     "expr": "imo_listener_ssl_handshake_total",
     "legendFormat": "{{__name__}}.{{envoy}}"
    },
    {
     "expr": "imo_listener_ssl_no_certificate_total",
     "legendFormat": "{{__name__}}.{{envoy}}"
    },
    {
     "expr": "imo_http_downstream_cx_ssl_active",
     "legendFormat": "{{__name__}}.{{envoy}}"
    },
    {
     "expr": "imo_http_downstream_cx_ssl_total",
     "legendFormat": "{{__name__}}.{{envoy}}"
    }
   ]
  }
 ]
}