{
 "title": "HTTP",
 "tags": [
  "imo",
  "protocol",
  "http"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "Completed requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "imo_listener_http_downstream_rq_completed_total{envoy_http_conn_manager_prefix!=\"l_otlp_stats\"}",
     "legendFormat": "{{envoy}}.{{envoy_http_conn_manager_prefix}}"
    }
   ]
  },
  {
   "title": "http return traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(imo_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix!=\"l_otlp_stats\"}[$__rate_interval])",
     "legendFormat": "{{envoy}}.{{envoy_http_conn_manager_prefix}}"
    }
   ]
  },
  {
   "title": "http traffic sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(imo_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix!=\"l_otlp_stats\"}[$__rate_interval])",
     "legendFormat": "{{envoy}}.{{envoy_http_conn_manager_prefix}}"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
   "targets": [
    { "service": "client" }
   ]
  }
 ]
}