{
 "title": "TCP",
 "tags": [
  "imo",
  "protocol",
  "tcp"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "TCP retransmissions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(envoy_listener_tcp_stats_cx_tx_retransmitted_segments{envoy_listener_address=\"0.0.0.0_18080\"}[$__rate_interval])",
     "legendFormat": "{{job}}.ds.tcp_tx_content"
    },
    {
     "expr": "irate(envoy_cluster_tcp_stats_cx_tx_retransmitted_segments{envoy_cluster_name=\"nginx_srvr_http1_unreliable\"}[$__rate_interval])",
     "legendFormat": "{{job}}.us.tcp_tx_req"
    },
    {
     "expr": "irate(onl_listener_tcp_stats_cx_tx_retransmitted_segments_total{envoy_listener_address=\"0.0.0.0_18080\"}[$__rate_interval])",
     "legendFormat": "{{node_id}}.ds.tcp_tx_content"
    },
    {
     "expr": "irate(onl_cluster_tcp_stats_cx_tx_retransmitted_segments_total{envoy_cluster_name=\"nginx_srvr_http1_unreliable\"}[$__rate_interval])",
     "legendFormat": "{{node_id}}.us.tcp_tx_req"
    },
    {
     "expr": "rate(imo_cluster_tcp_stats_cx_tx_retransmitted_segments_total[$__rate_interval])",
     "legendFormat": "from_{{envoy}}_to_{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Forward path",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(imo_cluster_tcp_stats_cx_tx_bytes_sent_total[$__rate_interval])",
     "legendFormat": "from_{{envoy}}_to_{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Unacked segments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "segments" } },
   "targets": [
    {
     "expr": "envoy_listener_tcp_stats_cx_tx_unacked_segments{envoy_listener_address=\"0.0.0.0_18080\"}",
     "legendFormat": "{{job}}.ds.tcp_tx_content"
    },
    {
     "expr": "envoy_cluster_tcp_stats_cx_tx_unacked_segments{envoy_cluster_name=\"nginx_srvr_http1_unreliable\"}",
     "legendFormat": "{{job}}.us.tcp_tx_req"
    },
    {
     "expr": "onl_listener_tcp_stats_cx_tx_unacked_segments{envoy_listener_address=\"0.0.0.0_18080\"}",
     "legendFormat": "{{node_id}}.ds.tcp_tx_content"
    },
    {
     "expr": "onl_cluster_tcp_stats_cx_tx_unacked_segments{envoy_cluster_name=\"nginx_srvr_http1_unreliable\"}",
     "legendFormat": "{{node_id}}.us.tcp_tx_req"
    },
    {
     "expr": "imo_cluster_tcp_stats_cx_tx_unacked_segments",
     "legendFormat": "from_{{envoy}}_to_{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Return path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(imo_listener_tcp_stats_cx_tx_bytes_sent_total[$__rate_interval])",
     "legendFormat": "from_{{envoy}}.{{envoy_listener_address}}"
    }
   ]
  },
  {
   "title": "Unsent bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "envoy_listener_tcp_stats_cx_tx_unsent_bytes{envoy_listener_address=\"0.0.0.0_18080\"}",
     "legendFormat": "{{job}}.ds.tcp_tx_content"
    },
    {
     "expr": "envoy_cluster_tcp_stats_cx_tx_unsent_bytes{envoy_cluster_name=\"nginx_srvr_http1_unreliable\"}",
     "legendFormat": "{{job}}.us.tcp_tx_req"
    },
    {
     "expr": "onl_listener_tcp_stats_cx_tx_unsent_bytes{envoy_listener_address=\"0.0.0.0_18080\"}",
     "legendFormat": "{{node_id}}.ds.tcp_tx_content"
    },
    {
     "expr": "onl_cluster_tcp_stats_cx_tx_unsent_bytes{envoy_cluster_name=\"nginx_srvr_http1_unreliable\"}",
     "legendFormat": "{{node_id}}.us.tcp_tx_req"
    },
    {
     "expr": "imo_cluster_tcp_stats_cx_tx_unsent_bytes",
     "legendFormat": "from_{{envoy}}_to_{{envoy_cluster_name}}"
    }
   ]
  }
 ]
}