{
 "title": "UDP",
 "tags": [
  "imo",
  "protocol",
  "udp"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "Active Sessions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(envoy) (imo_udp_downstream_sess_active)",
     "legendFormat": "{{envoy}}"
    }
   ]
  },
  {
   "title": "Datagrams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(imo_cluster_udp_sess_tx_datagrams_total[$__rate_interval])",
     "legendFormat": "{{envoy}} sending to {{envoy_cluster_name}}"
    },
    {
     "expr": "rate(imo_udp_downstream_sess_rx_datagrams_total[$__rate_interval])",
     "legendFormat": "{{envoy_udp_prefix}} receiving"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "imo_udp_downstream_sess_tx_errors_total",
     "legendFormat": "{{envoy}}.{{envoy_udp_prefix}}.transmit"
    },
    {
     "expr": "imo_udp_downstream_sess_rx_errors_total",
     "legendFormat": "{{envoy}}.{{envoy_udp_prefix}}.receive"
    }
   ]
  },
  {
   "title": "Datagram drops",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(envoy) (rate(imo_listener_udp_downstream_rx_datagram_dropped_total[$__rate_interval]))",
     "legendFormat": "{{envoy}}"
    }
   ]
  },
  {
   "title": "Trafiic received downstream",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(imo_udp_downstream_sess_rx_bytes_total[$__rate_interval])",
     "legendFormat": "{{envoy}}.{{envoy_udp_prefix}}"
    }
   ]
  },
  {
   "title": "Traffic sent upstream",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(imo_udp_downstream_sess_tx_bytes_total[$__rate_interval])",
     "legendFormat": "{{envoy}}.{{envoy_udp_prefix}}"
    }
   ]
  }
 ]
}